CatalogueTest : Fix failing tests on Windows
The two tests changed here need to have the catalogue in a `ScriptNode` in order for them to succeed. The failure message when the catalogue is just a Python object is :

======================================================================
FAIL: testRenamePromotedImages (GafferImageTest.CatalogueTest.CatalogueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "K:\build\gaffer\python\GafferTest\ParallelAlgoTest.py", line 81, in assertCalled
    f = self.__queue.get( block = True, timeout = timeout )
  File "K:\build\gaffer\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\build\gaffer\python\GafferImageTest\CatalogueTest.py", line 777, in testRenamePromotedImages
    self.sendImage( red["out"], box["catalogue"] )
  File "K:\build\gaffer\python\GafferImageTest\CatalogueTest.py", line 63, in sendImage
    h.assertCalled()
  File "K:\build\gaffer\python\GafferTest\ParallelAlgoTest.py", line 83, in assertCalled
    raise AssertionError( "UIThread call not made within {} seconds".format( timeout ) )
AssertionError: UIThread call not made within 30.0 seconds